### ISSUE TITLE
add space to habitation for walking and such

### ISSUE THREAD

**Issue by landonbw** [578mars/Matlab-Code#2]

**Comment by dkadams2** [comment]
I think that would be easy to fix, it would just be adding something like 1.5 meters or so to the length or width value reported by MIDACO to give them a hallway essentially (at least that seems reasonable to me). Also, I believe that I already accounted for the additional space required in the storage dome for water, food, and water recycling equipment. Other than that, I think I'll also just multiply vol_food4trip by two since currently it only looks at a one way trip
